### PR TITLE
Added async checking of inventories

### PR DESCRIPTION
**Pull request by FEFalk**
Solves alot of lag whenever the inventories update or when the player adds items to the crafting menu by using the plus button or Recipe tree function. Haven't tested much for any potential side effects yet.

### CODE REVIEW

**Comment by alikindsys** [comment]
Overall great change, the only problem I can see is that we're submitting work for a new thread even if the screen isn't a `MEStorageMenu` and returning an empty inventory if the task fails.

If I recall correctly, way back when I was developing this mod that check was needed because some screens in AppEng (or an addon mod, can't remember) don't extend that class and that was causing null references when trying to access information from the `StorageMenu` subclass.

Since getting an `EmiInventory` from a players' inventory is (usually) an cheap operation that EMI uses for their base-case, and players expect at least for their inventories to be available to EMI at all times, returning an empty inventory breaks that assumption.

I'd just keep the threading work for the inner path where Applied Energistics' inventories are fetched, since that can take quite some time, and lift the `instanceof` check to how it was originally. There is no reason to make that check (which is a simple fast jvm comparison) inside a task.

**Comment by FEFalk** [comment]
I see, that makes sense, thanks for the explanation :)
Tbh I just took a swing at it without any knowledge about the coding behind AE2.
I'll adjust it later today probably!

**Comment by FEFalk** [comment]
@alikindsys 
Alright, I have updated the code. Seems to be running smoothly for me still!

**Comment by FEFalk** [comment]
Sweet, my pleasure!

**Pull request merged**
